# Generated by Django 2.0.8 on 2018-08-15 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(default=1)),
                ('slot_timing', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Slot_List',
                'verbose_name_plural': 'Slot_List',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='slot_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbms.Slot_list'),
            preserve_default=False,
        ),
    ]
